import { PermissionFlagsBits, SlashCommandBuilder, type ChatInputCommandInteraction } from "discord.js";
import { getAutomodConfig, upsertAutomodConfig } from "../../modules/automod/repository.js";
import { clearAutomodConfigCache } from "../../modules/automod/service.js";
export const data=new SlashCommandBuilder().setName("automod").setDescription("Configura la protección automática.").setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild.toString())
.addSubcommand(s=>s.setName("activar").setDescription("Activa AutoMod.")).addSubcommand(s=>s.setName("desactivar").setDescription("Desactiva AutoMod.")).addSubcommand(s=>s.setName("estado").setDescription("Muestra el estado.")).addSubcommand(s=>s.setName("palabra").setDescription("Gestiona palabras bloqueadas.").addStringOption(o=>o.setName("accion").setDescription("Acción").setRequired(true).addChoices({name:"añadir",value:"add"},{name:"quitar",value:"remove"})).addStringOption(o=>o.setName("valor").setDescription("Palabra").setRequired(true).setMaxLength(100))).addSubcommand(s=>s.setName("patron").setDescription("Gestiona patrones bloqueados.").addStringOption(o=>o.setName("accion").setDescription("Acción").setRequired(true).addChoices({name:"añadir",value:"add"},{name:"quitar",value:"remove"})).addStringOption(o=>o.setName("valor").setDescription("Patrón o enlace").setRequired(true).setMaxLength(200))).addSubcommand(s=>s.setName("limites").setDescription("Configura spam y menciones.").addIntegerOption(o=>o.setName("mensajes").setDescription("Mensajes").setMinValue(2).setMaxValue(30)).addIntegerOption(o=>o.setName("ventana").setDescription("Segundos").setMinValue(2).setMaxValue(60)).addIntegerOption(o=>o.setName("menciones").setDescription("Menciones").setMinValue(1).setMaxValue(50))).addSubcommand(s=>s.setName("accion").setDescription("Configura la acción.").addStringOption(o=>o.setName("tipo").setDescription("Tipo").setRequired(true).addChoices({name:"Eliminar",value:"delete"},{name:"Eliminar + timeout",value:"timeout"})).addIntegerOption(o=>o.setName("segundos").setDescription("Timeout").setMinValue(10).setMaxValue(86400))).addSubcommand(s=>s.setName("raid").setDescription("Configura anti-raid.").addBooleanOption(o=>o.setName("activo").setDescription("Activo").setRequired(true)).addIntegerOption(o=>o.setName("entradas").setDescription("Umbral").setMinValue(3).setMaxValue(50)).addIntegerOption(o=>o.setName("ventana").setDescription("Segundos").setMinValue(5).setMaxValue(120)).addStringOption(o=>o.setName("accion").setDescription("Respuesta").addChoices({name:"Solo alertar",value:"alert"},{name:"Timeout",value:"timeout"},{name:"Expulsar",value:"kick"})).addIntegerOption(o=>o.setName("timeout").setDescription("Timeout anti-raid").setMinValue(10).setMaxValue(86400)).addBooleanOption(o=>o.setName("bloqueo").setDescription("Bloqueo de canales")));
export async function execute(i:ChatInputCommandInteraction){if(!i.guild){await i.reply({content:"Solo puede utilizarse dentro de un servidor.",ephemeral:true});return;}const s=i.options.getSubcommand(),cur=await getAutomodConfig(i.guild.id);if(s==="activar"||s==="desactivar"){const c=await upsertAutomodConfig(i.guild.id,{enabled:s==="activar"});
clearAutomodConfigCache(i.guild.id);await i.reply({content:"AutoMod "+(c.enabled?"activado.":"desactivado."),ephemeral:true});return;}if(s==="estado"){if(!cur){await i.reply({content:"AutoMod aún no está configurado.",ephemeral:true});return;}await i.reply({content:"Estado: **"+(cur.enabled?"Activo":"Inactivo")+"**\nAnti-raid: **"+(cur.raid_enabled?"Activo":"Inactivo")+"** ("+cur.raid_action+", "+cur.raid_join_threshold+"/"+cur.raid_window_seconds+"s)\nPalabras: **"+cur.bad_words.length+"**\nPatrones: **"+cur.blocked_patterns.length+"**\nSpam: **"+cur.max_messages+"/"+cur.message_window_seconds+"s**\nMenciones: **"+cur.max_mentions+"**\nAcción: **"+cur.action+"**",ephemeral:true});return;}if(s==="palabra"||s==="patron"){const a=i.options.getString("accion",true),v=i.options.getString("valor",true).trim(),key=s==="palabra"?"bad_words":"blocked_patterns",list=cur?.[key]??[],next=a==="add"?[...new Set([...list,v])]:list.filter(x=>x!==v);await upsertAutomodConfig(i.guild.id,{[key]:next});
clearAutomodConfigCache(i.guild.id);await i.reply({content:"Configuración actualizada.",ephemeral:true});return;}if(s==="limites"){const p:Record<string,number>={};const m=i.options.getInteger("mensajes"),w=i.options.getInteger("ventana"),n=i.options.getInteger("menciones");if(m!==null)p.max_messages=m;if(w!==null)p.message_window_seconds=w;if(n!==null)p.max_mentions=n;await upsertAutomodConfig(i.guild.id,p);
clearAutomodConfigCache(i.guild.id);await i.reply({content:"Límites actualizados.",ephemeral:true});return;}if(s==="accion"){const type=i.options.getString("tipo",true) as "delete"|"timeout",sec=i.options.getInteger("segundos");await upsertAutomodConfig(i.guild.id,{action:type,...(sec!==null?{timeout_seconds:sec}:{})});
clearAutomodConfigCache(i.guild.id);await i.reply({content:"Acción actualizada.",ephemeral:true});return;}const active=i.options.getBoolean("activo",true),e=i.options.getInteger("entradas"),w=i.options.getInteger("ventana"),a=i.options.getString("accion") as "alert"|"timeout"|"kick"|null,t=i.options.getInteger("timeout"),lock=i.options.getBoolean("bloqueo");await upsertAutomodConfig(i.guild.id,{raid_enabled:active,...(e!==null?{raid_join_threshold:e}:{}),...(w!==null?{raid_window_seconds:w}:{}),...(a?{raid_action:a}:{}),...(t!==null?{raid_timeout_seconds:t}:{}),...(lock!==null?{raid_lockdown:lock}:{})});
clearAutomodConfigCache(i.guild.id);await i.reply({content:"Configuración anti-raid actualizada.",ephemeral:true});}
