create table if not exists public.ticket_categories (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guilds(guild_id) on delete cascade,
  name text not null,
  description text,
  discord_category_id text,
  staff_role_ids text[] not null default '{}',
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  max_open_per_user integer not null default 1
    check (max_open_per_user between 1 and 20),
  auto_close_minutes integer
    check (auto_close_minutes is null or auto_close_minutes >= 5),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, name)
);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guilds(guild_id) on delete cascade,
  ticket_number bigint generated by default as identity,
  channel_id text not null unique,
  owner_id text not null,
  category_id uuid not null references public.ticket_categories(id) on delete restrict,
  status text not null default 'open'
    check (status in ('open', 'claimed', 'closed')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  claimed_by text,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  closed_at timestamptz
);

create index if not exists idx_ticket_categories_guild
  on public.ticket_categories(guild_id);

create index if not exists idx_tickets_guild_status
  on public.tickets(guild_id, status);

create index if not exists idx_tickets_owner_status
  on public.tickets(guild_id, owner_id, status);

alter table public.ticket_categories enable row level security;
alter table public.tickets enable row level security;

drop trigger if exists ticket_categories_set_updated_at on public.ticket_categories;
create trigger ticket_categories_set_updated_at
before update on public.ticket_categories
for each row execute function public.set_updated_at();