create table if not exists public.moderation_cases (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guilds(guild_id) on delete cascade,
  case_number bigint generated by default as identity,
  target_id text not null,
  moderator_id text not null,
  action text not null check (action in ('warn','timeout','kick','ban','unban')),
  reason text not null default 'Sin motivo especificado.',
  duration_seconds integer,
  status text not null default 'completed' check (status in ('completed','failed','pending')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists idx_moderation_cases_guild_case on public.moderation_cases(guild_id, case_number desc);
create index if not exists idx_moderation_cases_target on public.moderation_cases(guild_id, target_id, created_at desc);
create index if not exists idx_moderation_cases_moderator on public.moderation_cases(guild_id, moderator_id, created_at desc);
alter table public.moderation_cases enable row level security;

create table if not exists public.moderation_notes (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guilds(guild_id) on delete cascade,
  user_id text not null,
  staff_id text not null,
  note text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_moderation_notes_user on public.moderation_notes(guild_id, user_id, created_at desc);
alter table public.moderation_notes enable row level security;
